<a href="https://colab.research.google.com/github/FatimaMoqran/cours_Data_IA_simplon/blob/master/neural_network__l_layer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# importation des librairies

import numpy as np

In [0]:
# dataset Xor 
#nombres entiers 2 nombres (0 et 1) avec un array de taille (2,400)
X = np.random.randint(2, size=(2,400))
Y = np.logical_xor(X[0,:],X[1,:])


In [4]:
#print datas

X.shape


(2, 400)

In [5]:
Y.shape

(400,)

In [6]:
#numpy ne reconnais pas alors reshape
Y = Y.reshape(1,400)
Y.shape

(1, 400)

In [0]:
#m = nombre d'exemples


In [0]:
def sigmoid(Z):
  
  s = 1/(1+(np.exp(-Z)))
  
  return s

In [8]:
#test sigmoid

sigmoid(2)

0.8807970779778823

In [0]:
 # Z>0 c'est un test si Z>0 alors on va avoir 1 sinon on va avoir 0
  
def relu(Z):
  
    #r = Z * (Z>0)
    
    r = np.maximum(0,Z)
    
  
    return r

In [10]:
#test relu

relu(3)

3

In [0]:
#structure du neural network

#random seed pour avoir les même nombres aléatoires


np.random.seed(3)


#print(L)

def initialisation_deep(dim_layers):
    parameters={}
    
    L = len(dim_layers)
    
    for l in range(1,L):
    
      parameters[f'W{l}']= np.random.randn(dim_layers[l], dim_layers[l-1])*0.01
      
      parameters[f'b{l}'] = np.zeros((dim_layers[l],1))
    
    return parameters

#test sur les shapes des matrices:

    assert(parameters[f"W{l}"].shape == (dim_layers[l],dim_layers[l-1]))
    assert(parameters[f"b{l}"].shape == (dim_layers[l],1))



In [0]:
parameters = initialisation_deep([2,3,4,5,1])

In [13]:
parameters

{'W1': array([[ 0.01788628,  0.0043651 ],
        [ 0.00096497, -0.01863493],
        [-0.00277388, -0.00354759]]),
 'W2': array([[-0.00082741, -0.00627001, -0.00043818],
        [-0.00477218, -0.01313865,  0.00884622],
        [ 0.00881318,  0.01709573,  0.00050034],
        [-0.00404677, -0.0054536 , -0.01546477]]),
 'W3': array([[ 0.00982367, -0.01101068, -0.01185047, -0.0020565 ],
        [ 0.01486148,  0.00236716, -0.01023785, -0.00712993],
        [ 0.00625245, -0.00160513, -0.00768836, -0.00230031],
        [ 0.00745056,  0.01976111, -0.01244123, -0.00626417],
        [-0.00803766, -0.02419083, -0.00923792, -0.01023876]]),
 'W4': array([[ 0.01123978, -0.00131914, -0.01623285,  0.00646675, -0.00356271]]),
 'b1': array([[0.],
        [0.],
        [0.]]),
 'b2': array([[0.],
        [0.],
        [0.],
        [0.]]),
 'b3': array([[0.],
        [0.],
        [0.],
        [0.],
        [0.]]),
 'b4': array([[0.]])}

In [0]:
# forward propagate


#implémentation d'une forward simple 
#A ce sont les activations des couches précedentes 
#W les poids de chaque couches
#b les biais pour chaque couche

  
def forward_simple(A,W,b):
  
  Z = np.dot(W,A)+b

  
# rajoute un cache pour stocker mes variables
  cache = (A,W,b)
  
  return Z,cache




  assert (Z.shape == (W.shape[0], A.shape[1]))
  

In [15]:
A_test= np.array([
           [3,4,5],
           [3,4,7],
           [4,2,1]
                  ])
W_test= np.array([
                [5,3,1],
                [6,7,9],
                [3,5,2]
                       ])
b_test= ([
          [0],
          [0],
          [0]
             ])



Z,cache = forward_simple(A_test,W_test,b_test)

print(Z)

print(cache)

[[28 34 47]
 [75 70 88]
 [32 36 52]]
(array([[3, 4, 5],
       [3, 4, 7],
       [4, 2, 1]]), array([[5, 3, 1],
       [6, 7, 9],
       [3, 5, 2]]), [[0], [0], [0]])


In [0]:
def forward_activation (A_prev,W,b,activation):
    
  if activation == 'relu':
      
    Z,cache = forward_simple(A_prev,W,b)
        
    A = relu(Z)
        
  if activation == "sigmoid":
        
    Z,cache = forward_simple(A_prev,W,b)
        
    A = sigmoid(Z) 
        
    return A
  

In [17]:
A = forward_activation(A_test,W_test,b_test,re)lu

print(A)

SyntaxError: ignored

In [0]:
%debug



> /usr/local/lib/python3.6/dist-packages/IPython/core/compilerop.py(100)ast_parse()
     98         Arguments are exactly the same as ast.parse (in the standard library),
     99         and are passed to the built-in compile function."""
--> 100         return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)
    101 
    102     def reset_compiler_flags(self):

